let incomeExpenseChart,expenseCategoryChart,monthlySpendingChart,budgetActualChart;
document.addEventListener("DOMContentLoaded",()=>{if(document.body.dataset.page==="analytics")initAnalytics()});
function initAnalytics(){const p=document.getElementById("analyticsPeriod");p.addEventListener("change",()=>{document.getElementById("customRange").classList.toggle("hidden",p.value!=="custom");refreshAnalytics()});["analyticsFrom","analyticsTo"].forEach(id=>document.getElementById(id)?.addEventListener("change",refreshAnalytics));refreshAnalytics()}
function getPeriodTransactions(){const all=getTransactions(),now=new Date(),mode=document.getElementById("analyticsPeriod").value;let from,to;if(mode==="week"){from=new Date(now);from.setDate(now.getDate()-6);to=now}else if(mode==="month"){from=new Date(now.getFullYear(),now.getMonth(),1);to=now}else if(mode==="lastMonth"){from=new Date(now.getFullYear(),now.getMonth()-1,1);to=new Date(now.getFullYear(),now.getMonth(),0)}else if(mode==="3months"){from=new Date(now.getFullYear(),now.getMonth()-2,1);to=now}else if(mode==="6months"){from=new Date(now.getFullYear(),now.getMonth()-5,1);to=now}else if(mode==="year"){from=new Date(now.getFullYear(),0,1);to=now}else{from=new Date((document.getElementById("analyticsFrom").value||todayISO())+"T00:00:00");to=new Date((document.getElementById("analyticsTo").value||todayISO())+"T23:59:59")}return all.filter(t=>{const d=new Date(t.date+"T12:00:00");return d>=from&&d<=to})}
function refreshAnalytics(){const el=document.getElementById("incomeExpenseChart");if(!el)return;const tx=getPeriodTransactions(),inc=sumTx(tx,"income"),exp=sumTx(tx,"expense"),sav=inc-exp;setText("aIncome",formatMoney(inc));setText("aExpenses",formatMoney(exp));setText("aSavings",formatMoney(sav));setText("aRate",`${inc?(sav/inc*100).toFixed(0):0}%`);renderIncomeExpense(tx);renderExpenseCategory(tx);renderMonthly(tx);renderBudgetActual();renderAnalyticsInsights(tx)}
function renderIncomeExpense(tx){const ctx=document.getElementById("incomeExpenseChart"),groups={};tx.forEach(t=>{const k=t.date.slice(0,7);groups[k]??={income:0,expense:0};groups[k][t.type]+=t.amount});const keys=Object.keys(groups).sort();if(incomeExpenseChart)incomeExpenseChart.destroy();incomeExpenseChart=new Chart(ctx,{type:"bar",data:{labels:keys.map(k=>new Date(k+"-01").toLocaleDateString("en-IN",{month:"short",year:"numeric"})),datasets:[{label:"Income",data:keys.map(k=>groups[k].income),backgroundColor:"#16a34a",borderRadius:6},{label:"Expenses",data:keys.map(k=>groups[k].expense),backgroundColor:"#dc2626",borderRadius:6}]},options:chartOptions()})}
function renderExpenseCategory(tx){const ctx=document.getElementById("expenseCategoryChart"),map={};tx.filter(t=>t.type==="expense").forEach(t=>map[t.category]=(map[t.category]||0)+t.amount);const e=Object.entries(map).sort((a,b)=>b[1]-a[1]);if(expenseCategoryChart)expenseCategoryChart.destroy();expenseCategoryChart=new Chart(ctx,{type:"doughnut",data:{labels:e.map(x=>x[0]),datasets:[{data:e.map(x=>x[1]),backgroundColor:["#4f46e5","#16a34a","#d97706","#dc2626","#7c3aed","#0891b2","#db2777","#64748b"],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"bottom",labels:{font:{size:9},usePointStyle:true}},tooltip:{callbacks:{label:c=>`${c.label}: ${formatMoney(c.raw)}`}}}}})}
function renderMonthly(tx){const ctx=document.getElementById("monthlySpendingChart"),groups={};tx.filter(t=>t.type==="expense").forEach(t=>{const k=t.date.slice(0,7);groups[k]=(groups[k]||0)+t.amount});const keys=Object.keys(groups).sort();if(monthlySpendingChart)monthlySpendingChart.destroy();monthlySpendingChart=new Chart(ctx,{type:"line",data:{labels:keys.map(k=>new Date(k+"-01").toLocaleDateString("en-IN",{month:"short"})),datasets:[{label:"Expenses",data:keys.map(k=>groups[k]),borderColor:"#4f46e5",backgroundColor:"rgba(79,70,229,.1)",fill:true,tension:.35,pointRadius:3}]},options:chartOptions()})}
function renderBudgetActual(){const ctx=document.getElementById("budgetActualChart"),m=currentMonth(),bs=getBudgets().filter(b=>b.month===m);if(budgetActualChart)budgetActualChart.destroy();budgetActualChart=new Chart(ctx,{type:"bar",data:{labels:bs.map(b=>b.category),datasets:[{label:"Budget",data:bs.map(b=>b.amount),backgroundColor:"#c7d2fe",borderRadius:5},{label:"Actual",data:bs.map(b=>categorySpent(b.category,m)),backgroundColor:"#4f46e5",borderRadius:5}]},options:chartOptions()})}
function renderAnalyticsInsights(tx){const el=document.getElementById("analyticsInsights"),inc=sumTx(tx,"income"),exp=sumTx(tx,"expense"),map={};tx.filter(t=>t.type==="expense").forEach(t=>map[t.category]=(map[t.category]||0)+t.amount);const top=Object.entries(map).sort((a,b)=>b[1]-a[1])[0],items=[];if(top)items.push(["🏆","Top spending category",`${top[0]} accounts for ${formatMoney(top[1])} of expenses.`]);if(inc)items.push(["💰","Savings","You saved ${formatMoney(inc-exp)} in the selected period.`]);if(top&&exp)items.push(["📊","Share of spending",`${top[0]} represents ${(top[1]/exp*100).toFixed(0)}% of your expenses.`]);items.push(["🔎","Tip","Use budgets for your top categories to make spending more predictable."]);el.innerHTML=items.map(x=>`<div class="insight-box"><strong>${x[0]} ${x[1]}</strong><p>${x[2]}</p></div>`).join("")}
