document.addEventListener("DOMContentLoaded",()=>{ensureInitialized();applyTheme();initGlobalUI();if(document.body.dataset.page)loadProfileUI();if(document.body.classList.contains("landing"))initLanding()});
function initials(name){return (name||"User").trim().split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase()}
function applyTheme(){const dark=localStorage.getItem(SPENDLY_KEYS.theme)==="dark";document.body.classList.toggle("dark",dark);document.querySelectorAll("#themeToggle,#settingsTheme").forEach(el=>{if(el.id==="settingsTheme")el.classList.toggle("on",dark);else{const i=el.querySelector("i");if(i)i.style.background=dark?"var(--primary)":"";}});const label=document.getElementById("themeLabel");if(label)label.textContent=dark?"Light mode":"Dark mode"}
function toggleTheme(){const dark=document.body.classList.toggle("dark");localStorage.setItem(SPENDLY_KEYS.theme,dark?"dark":"light");applyTheme();if(window.refreshCharts)window.refreshCharts()}
function loadProfileUI(){const u=getUser();const init=initials(u.name);["sideAvatar","topAvatar"].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=init});["sideUser","topUser"].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=u.name.split(" ")[0]});const email=document.getElementById("sideEmail");if(email)email.textContent=u.email;const g=document.getElementById("greeting");if(g)g.textContent=`Good ${new Date().getHours()<12?"morning":new Date().getHours()<18?"afternoon":"evening"}, ${u.name.split(" ")[0]} 👋`}
function initGlobalUI(){const t=document.getElementById("themeToggle");if(t)t.addEventListener("click",toggleTheme);const st=document.getElementById("settingsTheme");if(st)st.addEventListener("click",toggleTheme);const menu=document.getElementById("menuBtn"),side=document.getElementById("sidebar"),overlay=document.getElementById("mobileOverlay");if(menu)menu.addEventListener("click",()=>{side.classList.toggle("open");overlay.classList.toggle("show")});if(overlay)overlay.addEventListener("click",()=>{side.classList.remove("open");overlay.classList.remove("show")});const logout=document.getElementById("logoutBtn");if(logout)logout.addEventListener("click",()=>{showToast("Demo session ended. Returning to landing page.");setTimeout(()=>location.href="index.html",500)});document.querySelectorAll("[data-close]").forEach(x=>x.addEventListener("click",()=>closeModal(x.closest(".modal-backdrop"))));document.querySelectorAll(".modal-backdrop").forEach(m=>m.addEventListener("click",e=>{if(e.target===m)closeModal(m)}));document.addEventListener("keydown",e=>{if(e.key==="Escape")document.querySelectorAll(".modal-backdrop.open").forEach(closeModal)});const n=document.getElementById("notificationBtn");if(n)n.addEventListener("click",()=>showNotifications())}
function openModal(id){const m=document.getElementById(id);if(m)m.classList.add("open")}
function closeModal(m){if(m)m.classList.remove("open")}
function showToast(message,type="success"){const c=document.getElementById("toastContainer");if(!c)return;const d=document.createElement("div");d.className=`toast ${type}`;d.textContent=(type==="success"?"✓ ":type==="error"?"! ":"")+message;c.appendChild(d);setTimeout(()=>d.remove(),3000)}
function showNotifications(){const tx=getTransactions(),bud=getBudgets(),goals=getGoals(),ym=monthKey(new Date()),notes=[];bud.filter(b=>b.month===ym).forEach(b=>{const spent=tx.filter(t=>t.type==="expense"&&t.category===b.category&&t.date.startsWith(ym)).reduce((s,t)=>s+t.amount,0),pct=b.amount?spent/b.amount*100:0;if(pct>=100)notes.push(`Budget exceeded: ${b.category} is at ${Math.round(pct)}%.`);else if(pct>=90)notes.push(`Budget warning: ${b.category} is ${Math.round(pct)}% used.`)});goals.forEach(g=>{const p=g.target?g.current/g.target*100:0;if(p>=50&&p<100)notes.push(`Goal update: ${g.name} reached ${Math.round(p)}%.`)});const big=tx.filter(t=>t.type==="expense"&&t.amount>=5000).sort((a,b)=>b.amount-a.amount)[0];if(big)notes.push(`Large expense: ${big.description} was ${formatMoney(big.amount)}.`);if(!notes.length)notes.push("You're all caught up. No important alerts right now.");showToast(notes[0]);}
function initLanding(){const b=document.getElementById("loginBtn"),m=document.getElementById("authModal"),f=document.getElementById("authForm");if(b)b.onclick=()=>openModal("authModal");if(f)f.addEventListener("submit",e=>{e.preventDefault();const u=getUser();u.email=document.getElementById("authEmail").value;saveUser(u);closeModal(m);location.href="dashboard.html"})}
function currentMonth(){return monthKey(new Date())}
function sumTx(txs,type){return txs.filter(t=>t.type===type).reduce((s,t)=>s+Number(t.amount),0)}
function monthTransactions(month){return getTransactions().filter(t=>t.date.startsWith(month))}
function categorySpent(category,month){return monthTransactions(month).filter(t=>t.type==="expense"&&t.category===category).reduce((s,t)=>s+t.amount,0)}
function daysRemaining(date){const d=new Date(date+"T00:00:00"),n=new Date();return Math.max(0,Math.ceil((d-new Date(n.getFullYear(),n.getMonth(),n.getDate()))/86400000))}
