let cashflowChart,categoryChart;
document.addEventListener("DOMContentLoaded",()=>{if(document.body.dataset.page==="dashboard")initDashboard()});
function initDashboard(){const sel=document.getElementById("dashboardMonth");const now=new Date();const months=[];for(let i=0;i<6;i++){const d=new Date(now.getFullYear(),now.getMonth()-i,1);months.push(monthKey(d))}sel.innerHTML=months.map(m=>`<option value="${m}">${new Date(m+"-01").toLocaleDateString("en-IN",{month:"long",year:"numeric"})}</option>`).join("");sel.value=currentMonth();sel.addEventListener("change",refreshDashboard);document.getElementById("quickAddTx").onclick=()=>openTransaction();refreshDashboard()}
function refreshDashboard(){const m=document.getElementById("dashboardMonth")?.value||currentMonth(),tx=getTransactions(),mt=tx.filter(t=>t.date.startsWith(m)),income=sumTx(mt,"income"),expense=sumTx(mt,"expense"),balance=sumTx(tx,"income")-sumTx(tx,"expense"),save=income-expense,rate=income?save/income*100:0;setText("statBalance",formatMoney(balance));setText("statIncome",formatMoney(income));setText("statExpenses",formatMoney(expense));setText("statSavings",`${rate.toFixed(0)}%`);setText("savingsMeta",save>=0?`${formatMoney(save)} saved this month`:`${formatMoney(Math.abs(save))} over income`);setText("monthLabel",new Date(m+"-01").toLocaleDateString("en-IN",{month:"long",year:"numeric"}));renderCashflow(m);renderBudgets(m);renderRecent();renderCategory(m);renderDashboardInsights(m)}
function renderCashflow(m){const ctx=document.getElementById("cashflowChart");if(!ctx)return;const [y,mo]=m.split("-").map(Number),days=new Date(y,mo,0).getDate(),labels=[],income=[],expense=[];for(let d=1;d<=days;d++){const ds=`${m}-${String(d).padStart(2,"0")}`;labels.push(d);income.push(getTransactions().filter(t=>t.date===ds&&t.type==="income").reduce((s,t)=>s+t.amount,0));expense.push(getTransactions().filter(t=>t.date===ds&&t.type==="expense").reduce((s,t)=>s+t.amount,0))}if(cashflowChart)cashflowChart.destroy();cashflowChart=new Chart(ctx,{type:"line",data:{labels,datasets:[{label:"Income",data:income,borderColor:"#16a34a",backgroundColor:"rgba(22,163,74,.08)",fill:true,tension:.35,pointRadius:0},{label:"Expenses",data:expense,borderColor:"#dc2626",backgroundColor:"rgba(220,38,38,.06)",fill:true,tension:.35,pointRadius:0}]},options:chartOptions()})}
function renderBudgets(m){const el=document.getElementById("dashboardBudgets");const bs=getBudgets().filter(b=>b.month===m);if(!bs.length){el.innerHTML='<div class="empty-state"><p>No budgets for this month.</p><a class="text-link" href="budgets.html">Create one →</a></div>';return}const total=bs.reduce((s,b)=>s+b.amount,0),spent=bs.reduce((s,b)=>s+categorySpent(b.category,m),0);setText("budgetOverviewText",`${formatMoney(spent)} of ${formatMoney(total)} used`);el.innerHTML=bs.slice(0,5).map(b=>{const s=categorySpent(b.category,m),p=b.amount?s/b.amount*100:0,c=p>=100?"danger":p>=75?"warning":"";return `<div class="budget-mini"><div class="budget-mini-top"><span>${categoryIcons[b.category]||"•"} ${b.category}</span><small>${formatMoney(s)} / ${formatMoney(b.amount)}</small></div><div class="progress ${c}"><span style="width:${Math.min(p,100)}%"></span></div></div>`}).join("")}
function renderRecent(){const el=document.getElementById("recentTransactions");el.innerHTML=getTransactions().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6).map(t=>`<div class="transaction-item"><span class="tx-icon">${categoryIcons[t.category]||"•"}</span><div class="tx-main"><strong>${escapeHtml(t.description)}</strong><small>${t.category} · ${formatDate(t.date)}</small></div><span class="tx-amount ${t.type}">${t.type==="income"?"+":"-"}${formatMoney(t.amount)}</span></div>`).join("")}
function renderCategory(m){const ctx=document.getElementById("categoryChart");if(!ctx)return;const map={};monthTransactions(m).filter(t=>t.type==="expense").forEach(t=>map[t.category]=(map[t.category]||0)+t.amount);const entries=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,6);if(categoryChart)categoryChart.destroy();categoryChart=new Chart(ctx,{type:"doughnut",data:{labels:entries.map(x=>x[0]),datasets:[{data:entries.map(x=>x[1]),backgroundColor:["#4f46e5","#16a34a","#d97706","#dc2626","#7c3aed","#0891b2"],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:"72%",plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${c.label}: ${formatMoney(c.raw)}`}}}}});const leg=document.getElementById("categoryLegend");leg.innerHTML=entries.map((x,i)=>`<div class="legend-item"><i class="legend-dot" style="background:${["#4f46e5","#16a34a","#d97706","#dc2626","#7c3aed","#0891b2"][i]}"></i><span>${x[0]}</span><strong>${formatMoney(x[1])}</strong></div>`).join("")}
function renderDashboardInsights(m){const el=document.getElementById("dashboardInsights"),tx=monthTransactions(m).filter(t=>t.type==="expense"),income=sumTx(monthTransactions(m),"income"),expense=sumTx(monthTransactions(m),"expense");const map={};tx.forEach(t=>map[t.category]=(map[t.category]||0)+t.amount);const top=Object.entries(map).sort((a,b)=>b[1]-a[1])[0];el.innerHTML=`<h3>✨ Quick insights</h3><div class="insight-row"><span>💡</span><p>${top?`Your highest spending category is <strong>${top[0]}</strong> at ${formatMoney(top[1])}.`:"Add some expenses to unlock spending insights."}</p></div><div class="insight-row"><span>${income>=expense?"💰":"⚠️"}</span><p>${income?`You ${income>=expense?"saved":"spent"} <strong>${formatMoney(Math.abs(income-expense))}</strong> this month.`:"No income recorded for this month yet."}</p></div>`}
function setText(id,v){const e=document.getElementById(id);if(e)e.textContent=v}
function chartOptions(){return {responsive:true,maintainAspectRatio:false,interaction:{intersect:false,mode:"index"},plugins:{legend:{labels:{font:{size:10},usePointStyle:true}}},scales:{x:{grid:{display:false},ticks:{font:{size:9}}},y:{beginAtZero:true,grid:{color:"rgba(148,163,184,.12)"},ticks:{font:{size:9},callback:v=>formatMoney(v)}}}}}
